import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
 
/**
 * By the way, I first made django directory to set up backend environment.
 * And inside of 'backend' directory, i made virtual environment inside of 'djangobnb_backend'
 * directory and named it '.venv'. And i also pip installed django after activate virtual 
 * environment. Reason is i thought using virtual environment would better to deal with docker.
 */

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DjangoBnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
